apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: openshift-config
spec:
  commonName: api.w8vz2.dynamic.redhatworkshops.io:6443
  dnsNames:
  - api.w8vz2.dynamic.redhatworkshops.io:6443