apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: openshift-config
spec:
  commonName: api.8ktpb.dynamic.redhatworkshops.io
  dnsNames:
  - api.8ktpb.dynamic.redhatworkshops.io