apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts: 
    namedCertificates:
      - names: 
          - api.8ktpb.dynamic.redhatworkshops.io
        servingCertificate: 
          name: custom-certs-managed