apiVersion: v1
kind: Secret
metadata:
  name: ca-root-secret
  namespace: cert-manager
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFGTCCAwGgAwIBAgIUC3ZOmJRIqC90/f9HRzBkNKSGQFMwDQYJKoZIhvcNAQEN
    BQAwHDEaMBgGA1UEAwwRc3BlbnNjb3QuZGRucy5uZXQwHhcNMjUxMjExMDEyNTE5
    WhcNMzUxMjA5MDEyNTE5WjAcMRowGAYDVQQDDBFzcGVuc2NvdC5kZG5zLm5ldDCC
    AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAPAQQPZ71kGoySOMFi1bRS0j
    T08TxI922xivB3Sf9BsIYYVGMO0dG52OZCpimi4jxMs6igYbwlx6/47dvRYLkV4d
    QAgW9noUjEGA55BgtEn8fBA1QXe5XjECsogXcxGoODhZlyYJ6SrIzeiyyayiV79T
    0vzea8RojM2rjHL5mXTnc4/VfIp63wGj6HYvMhhDbZMbZYam/jt68E7RX8vnXhTT
    N3M7ddWQLeAgMY7PMGtobVYq8iXy/4LKp38vOD7Hl+BcwChtUtA58EP6lAMTb0n/
    OKZD5h806eK/XOTZKQTzsl+kwA3r/btPp5gDMtTIr0/BSolt5k7FIqxcKYXPBRMH
    oEJsqdewVccq3IUDrhO6aKr/GB2iLwXjycglLe0NN7Gt3RjHVdL39tUv0BPHBP4U
    u3Bqye3f8xBZNg7adTAXN/W0Fs01mVoI1BuZp4scei/TFDBf8g3jWxGuIIFeGyCa
    ArJdR/P29OxeZ/5bK+sdBJwx+d9lDnxAE/UBWrm5Vr5lS/ROGauU7zI+TuyGNeZ1
    QAT3AWf58d88o0ZIndLaGIshFBMq+CfCEPfVLo24DZyPjdgr9rTB3LC6n72YgPnY
    fvJwWhffyx5pJhYVExmOmub0E2/7liVvPcnTv5vluSB21gUGSdtvlDFky6NlaEf3
    wAY+H5G50t+as/spo1hlAgMBAAGjUzBRMB0GA1UdDgQWBBTX9RErEhJe2ndHy3vU
    IcN26xxzlTAfBgNVHSMEGDAWgBTX9RErEhJe2ndHy3vUIcN26xxzlTAPBgNVHRMB
    Af8EBTADAQH/MA0GCSqGSIb3DQEBDQUAA4ICAQDDMNMO7/4Zx3P6ngEgosnPLAH3
    ni0w7Fy8/QsqD1o/VAjZEjop8cPCwmQwxKs3YPb8la23du5bRM0hoH4MPMjcl7LA
    2uGyD9ZDAS+yyeplcxXSbJVVcu5PKgHoyUqzS5q8pjPgQtFaFS9DsxJkDPva2Ads
    Mkplz3xbgyKWGLX/Me3LA2clOjO43pHv8iwC3JHPnXYE2ad+ucnZrfUlsaVfZamA
    ZfOHF4ARlKJkFM3cGDvqfn6r8gaiHz2weB1jAU9uzRwLHP5L4CH3dYo+H9MIkwwS
    UiNaqZb787RrOYj5jvt5RzGr5xmWAERpDiF/7xbSGCue2WOOtgDarNpsTFYcVoxZ
    VC3WGMkO65y7vuIeKt0Lt3DzrZt4t6VGjnnhBi/rHT8pwJy9gCjJ+1CHpsIkZTOG
    6ruK9XEVZ0RTKzAGrP1ckUkNkwH0uG1zoNSR6mcGcNyUac18aS8yWg8BPt1JIsol
    3G7o//iH1LvgAYLkJ2Kd2WsK02YWl9K3RbXpFrhcgYkN9lLV4ojjN3OH53RBL0rg
    ywQIgRqprp3Gk4+WgF5DiZpO5TvmZoEUzNSi5Irhdlh0iSt+NZI9tn8LjuhIdy2M
    eGDA/tbW3vZwAx5bK+N+qd4L1BhT98jjQUnux3YdLScS5xfYooT1yhp1ge5pNKIQ
    E4NPvVtMrYOuYgZW8w==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJRAIBADANBgkqhkiG9w0BAQEFAASCCS4wggkqAgEAAoICAQDwEED2e9ZBqMkj
    jBYtW0UtI09PE8SPdtsYrwd0n/QbCGGFRjDtHRudjmQqYpouI8TLOooGG8Jcev+O
    3b0WC5FeHUAIFvZ6FIxBgOeQYLRJ/HwQNUF3uV4xArKIF3MRqDg4WZcmCekqyM3o
    ssmsole/U9L83mvEaIzNq4xy+Zl053OP1XyKet8Bo+h2LzIYQ22TG2WGpv47evBO
    0V/L514U0zdzO3XVkC3gIDGOzzBraG1WKvIl8v+Cyqd/Lzg+x5fgXMAobVLQOfBD
    +pQDE29J/zimQ+YfNOniv1zk2SkE87JfpMAN6/27T6eYAzLUyK9PwUqJbeZOxSKs
    XCmFzwUTB6BCbKnXsFXHKtyFA64Tumiq/xgdoi8F48nIJS3tDTexrd0Yx1XS9/bV
    L9ATxwT+FLtwasnt3/MQWTYO2nUwFzf1tBbNNZlaCNQbmaeLHHov0xQwX/IN41sR
    riCBXhsgmgKyXUfz9vTsXmf+WyvrHQScMfnfZQ58QBP1AVq5uVa+ZUv0ThmrlO8y
    Pk7shjXmdUAE9wFn+fHfPKNGSJ3S2hiLIRQTKvgnwhD31S6NuA2cj43YK/a0wdyw
    up+9mID52H7ycFoX38seaSYWFRMZjprm9BNv+5Ylbz3J07+b5bkgdtYFBknbb5Qx
    ZMujZWhH98AGPh+RudLfmrP7KaNYZQIDAQABAoICAAWeK8GuO4uvz9KFeGNkARDB
    rx0c9lBGf3FqxH7l212NQFL7xdtWqgscMPCOUX4GQkMLQf2gmqzKsr5SJsGkUFOR
    KwAazCEmkp2vJDwhtzZgB+XiiSoBwYLeGvV1BFwDwW+4JlcH4QKqTlSavSjNZ8ZH
    cjw5VvDyuBDRaekAOadzCdDyNbGRQd9qSYoH0rafT/94TajtXC0M1HYpD4KDDero
    18xaNjNi5gqaVkPkSgV0HSg+EF/zpCfDEaZioYCpRRRFYg3QI8xRqXNoeBxA+9gR
    y+6VejDSw9fAPgPw/QproDSoHgJ1ZQEEJ9o2gPMFJe0fizH/dhCegRA4MT87Yqqi
    uvHFF8LjcEzoMm1Uj4TIpC4AoPwbcmim+B3/gbDRP2fRqfSOUcHn8+vPM7ykTJTv
    H3rwJEAMAuqXHiFZKTCe5EmRTTVorOjmq3RiEWN/UJWcEMLXcKEi3LLFXVeJTY5u
    sXAV6RW/xn3a/mQWtu9nxBFKKaf/Nqao4Dn3R6Oz3DnzTHZnqcIQ6ohC0kmwF45A
    h2pM7yKBJyHAi7C3tAvx+reUgx8um0SqtEe7TRZXnQe+g6aNItjt+6LR5tihrORf
    pijfuXfQq7rCrZfxDM1or/WkMEyaaip0VYRF4Eak6dH5ZOht3w4TIm8McI/zudWF
    9DXkP5YcSTo2xF0CAPxBAoIBAQD/w+DyawZ/eYu9nHQbTz+IgU8pD/huDARuY9vf
    r/uOB9vykXihZl9jLUqlhY+3RDcy0eJEY2QnhopYkkE/NB1uJrJcM0II7axyg7mb
    LqnyTmGFFnv67PQ5rBGY+rOhDbGqHxWIuYFPS2j8BywDJpkucu1Nv4pVblj/i6Be
    i9oAB2Q04cGgXEM2pvOJhNdo1nuTy35Bwp154wLdDsrMXqF0EQpGIuQv62X8OcbG
    0iGg4QZcED0vLRpUnVcUknxcbZig+TqmC49lCccpy2jxE+8bA5WSuYaJcaaE3R5o
    ewOGYwWoWsmZaKxb2sU3eN9q6hJXsj/Zpylr1cjsR12sCzw1AoIBAQDwSK8lFUHU
    IeQ2HF5OGw6zm1uze0DI40gAtCiJbMCLOToYQIQ6BlZrJEYxkLQ9ZW6+As5BPkda
    kLNJr7Afz2/JzJUJMgtjeoHeXToRigibfw5ZZBkR0KWSOynNWmZrIoJs0p+qWlB1
    qD1O3PDfY5wmaI5NuwBJjMvPKDYBS5D3I1Ekt5ZPH+FUHIm0pGKAmA6rwyyRgeAY
    oNIUAKiLMp8PkLrLPuh5cc8vycPnjfIfLgeBNabf2ADG9MUONch22wIX4qktH0Kg
    xxxsa1IPyVdFdagK87xemIb0nsYdx+4jR2D9EmFMI1lU9fvqnsKYUu9/mrywrFC8
    Cz++oWZKPVFxAoIBAQDWnbZXlQk51HM3I16mP+SPFfqn+Te8mCbrvq2U0SYj82JT
    9E+mF7I5FZtKs316CirLYSUdv80eAZ57XhaUA5YihSQri/OAbHfFC9Wmawy+P5lD
    RS+5yjXRYxrNJKmwnj4UA8tdFFR2hk/NE/ORnUTynguUrwJUV6kknjRuwamnVox2
    d22zs1fPN16qaacb2MaPqTUD11uvGJehiTURMuMF8vqNCeAyebP1Z0HuOgtv5QMi
    I5pDyPQMRo74u0bRhEGL6jaVeKPV49OUtZQUn2aHY4WSPk2vbYeOe8F1aKv3i4YG
    1E/Qg+4FkdjliG7pVwsXPYKoj8WJMDZOVkA7Cp51AoIBAQDD+cQ/7pJ+PhYvu/t+
    oLrg6nlkbcZtElKLoGTfkP+JjedAGH7ABKM/R5qommknGi+0cf1fYTg5OYPBObXg
    fAOlB2MW2OZJAIYjos3VuEtE5+AAMI/x48bm+bIidvTJtJ/DuhXXj0nIbKt0QueC
    i2+0M9q8sySM2HTyRM2nSMa3iuqHk+TYLBxPyebWmqxsTZjJpqoXE2J/M8uj3NWa
    knMA8v4m/uwFAToGs/1AQpmTrKsaS3QLZdVccA64hE04A3A1ovxwfOqOz1bzZqTL
    k1/GmyuvoxOj46tOoKDdcU9dHr6QKgmJW9tkXCxXM51rN1l3LfFv91rxxAr9pA4V
    xuVBAoIBAQCT4lZwIzJD2TyzpNDuUMIARK4xomuhjGzTOSNr5//Z2TjVPBI5W1tk
    nBacL5q444ajZwTsB/oElhw3+nwgwXQpm4w2QdmdhGkes5jHWs3RupJaoDhT28J3
    cAn7jm/wKUrhT/lLirFVrICnIBVmlsns1WIielRqjZBjARHrx2LeUhO77jvGRdTB
    /Ie7Ic++Ff0SJDJAsbIuXkHbz4FtfNjxb4Je3BRhjZuXjxyaUyWkka7MIFip0V7h
    NqQKVkPhJ8ToGgwACFcXDeuIsqwiF8wHYOdxF29aiOWkYOE7gVbFV3BT+OZ+/l0o
    SaC0ZiW5Qwy/x6NAymrTBFGFVcG8MDrg
    -----END PRIVATE KEY-----
type: kubernetes.io/tls
