apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap-custom-ca.yaml
- proxy-cluster.yaml

patches:
- path: cert-manager-certificate-policy-patch.yaml
  target:
    kind: "ValidatingAdmissionPolicy"
    name: cert-manager-certificate-policy