apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap-cluster-ca.yaml
- proxy-cluster.yaml

patchesStrategicMerge:
- cert-manager-ca-root-secret-patch.yaml
