apiVersion: v1
kind: Secret
metadata:
  name: ca-root-secret
  namespace: cert-manager
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    -----END PRIVATE KEY-----
type: kubernetes.io/tls
