apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager-namespace.yaml
- cert-manager-og.yaml
- cert-manager-sub.yaml
- cert-manager-ca-root-secret.yaml
- cert-manager-cluster-issuer.yaml