apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- cnpg-sub.yaml
- cnpg-cluster.yaml
- quay-database-extension-enable-job.yaml

patches:
# Turn off the Quay managed database
- patch: |-
    apiVersion: quay.redhat.com/v1
    kind: QuayRegistry
    metadata:
      name: quay-registry
      namespace: quay
    spec:
      components:
      - kind: postgres
        managed: false   
