apiVersion: v1
kind: Secret
metadata:
  name: htpasswd
  namespace: openshift-config
type: Opaque
stringData:
  htpasswd: |
    admin:$2y$05$ZxaiWWf02NB6e/.Ym3GjGuvJJg6M7w1KYyJp8yCJcPEQsgYWLNZga
    craig:$2y$05$X49sJX2IqaBgR8JDvP2BwOphIig78buN10q9bNeW5MUuqqGbYfV2a
    developer:$apr1$1Q/n9xaE$L3LhUCr2JRUWaNEN3fZrO/
    release:$2y$05$iKWgk5ScAlyiZ/UZskcXu.0PeDYK5RV9Z.vFqfeGWLt5lGTqLJ2ra