apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: logging-loki-clf
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  managementState: Managed
  outputs:
    - lokiStack:
        authentication:
          token:
            from: serviceAccount
        target:
          name: lokistack-logging
          namespace: openshift-logging
      name: lokistack-logging
      tls:
        ca:
          configMapName: openshift-service-ca.crt
          key: service-ca.crt
      type: lokiStack
  pipelines:
    - inputRefs:
        - application
        - infrastructure
      name: logs-to-loki
      outputRefs:
        - lokistack-logging
  serviceAccount:
    name: cluster-logging-sa