apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
#  name: lokistack-logging
  name: lokistack-logging-audit
  namespace: openshift-logging
spec:
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
    - effectiveDate: '2024-10-01'
      version: v13
    secret:
      #name: lokistack-logging-secret
      name: lokistack-logging-audit-secret
      type: s3
  storageClassName: thin-csi
  tenants:
    mode: openshift-logging
