apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: lokistack-logging-secret
  namespace: openshift-logging
stringData:
  bucketnames: "loki-bucket"
  endpoint: "http://nfs.spenscot.ddns.net:9000"
  access_key_id: "qx2P8iyolybPfkk06eId"
  access_key_secret: "qdxYbXMBoiubNMLr4eisYp7Pixkwez7uFdDSxzuP"
type: opaque