apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
  name: logging-loki
  namespace: openshift-logging
spec:
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
    - effectiveDate: '2024-10-01'
      version: v13
    secret:
      name: logging-loki-secret
      type: s3
  storageClassName: nfs-client
  tenants:
    mode: openshift-logging