apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: openshift-config
spec:
  commonName: api.ocp4.spenscot.ddns.net:6443
  dnsNames:
  - api.ocp4.spenscot.ddns.net:6443