apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts: 
    namedCertificates:
      - names: 
          - api.disc.spenscot.ddns.net
        servingCertificate: 
          name: custom-certs-managed