apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-gitops
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      jsonnet: {}
#      recurse: false
    path: application-gitops
    repoURL: https://github.com/crscottau/ocp-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}