apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quay
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  source:
#    directory:
#      jsonnet: {}
#      recurse: false
    path: quay/base
    repoURL: https://github.com/crscottau/ocp-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}