apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: quay-registry
  namespace: quay
  annotations:
    argocd.argoproj.io/sync-wave: "20"  
spec:
  configBundleSecret: quay-registry-config-bundle
  components:
  - kind: clair
    managed: true
