apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-config-bundle
  namespace: quay
stringData:
  # Add FEATURE_PROXY_CACHE to default set
  # Add DISTRIBUTED_STORAGE* to use existing S3 storage
  config.yaml: |
    ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
    AUTHENTICATION_TYPE: Database
    DEFAULT_TAG_EXPIRATION: 2w
    DISTRIBUTED_STORAGE_CONFIG:
      s3Storage:
        - S3Storage
        - host: s3.ap-southeast-1.amazonaws.com
          s3_access_key: ********************
          s3_secret_key: ********************
          s3_bucket: quaybucket
          s3_region: ap-southeast-1
          storage_path: /datastorage/registry
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
    DISTRIBUTED_STORAGE_PREFERENCE:
    - s3Storage 
    ENTERPRISE_LOGO_URL: /static/img/RH_Logo_Quay_Black_UX-horizontal.svg
    FEATURE_BUILD_SUPPORT: false
    FEATURE_DIRECT_LOGIN: true
    FEATURE_MAILING: false
    FEATURE_PROXY_CACHE: true
    REGISTRY_TITLE: Red Hat Quay
    REGISTRY_TITLE_SHORT: Red Hat Quay
    SETUP_COMPLETE: true
    SUPER_USERS:
    - admin
    TAG_EXPIRATION_OPTIONS:
    - 2w
    TEAM_RESYNC_STALE_TIME: 60m
    TESTING: false
type: Opaque
