apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: quay-operator
  namespace: quay
spec:
  channel: stable-3.13
  installPlanApproval: Automatic
  name: quay-operator
  source: cs-redhat-operator-index-v4-16
  sourceNamespace: openshift-marketplace
