apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: application-1-dev
  namespace: application-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"  
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: application 1 development GitOps Project
  destinations:
    - name: in-cluster
      namespace: application-*
      server: 'https://kubernetes.default.svc'
  roles:
    - description: Group to developers to deploy on DEV environment
      groups:
        - developers
      name: developers
      policies:
        - p, proj:application-1-dev:developers, applications, get, application-*/*, allow
        - p, proj:application-1-dev:developers, applications, create, application-*/*, allow
        - p, proj:application-1-dev:developers, applications, update, application-*/*, allow
        - p, proj:application-1-dev:developers, applications, delete, application-*/*, allow
        - p, proj:application-1-dev:developers, applications, sync, application-*/*, allow
        - p, proj:application-1-dev:developers, applications, override, application-*/*, allow    
    - description: Group for production deployment
      groups:
        - release-coordinators
      name: release-coordinators
      policies:
        - p, proj:application-1-dev:release-coordinators, applications, get, application-*/*, allow
        - p, proj:application-1-dev:release-coordinators, applications, create, application-*/*, deny
        - p, proj:application-1-dev:release-coordinators, applications, update, application-*/*, deny
        - p, proj:application-1-dev:release-coordinators, applications, delete, application-*/*, deny
        - p, proj:application-1-dev:release-coordinators, applications, sync, application-*/*, deny
        - p, proj:application-1-dev:release-coordinators, applications, override, application-*/*, deny
  sourceRepos:
    - 'https://github.com/crscottau/*'          
