apiVersion: v1
kind: Secret
metadata:
  name: serviceaccount-central-secret
  namespace: central
  annotations:
    kubernetes.io/service-account.name: "central" 
type: kubernetes.io/service-account-token 
