apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: name 
    mappingMethod: method
    type: HTPasswd
    htpasswd:
      fileData:
        name: secret