apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- acm-acs-securedcluster-application.yaml
- acm-application.yaml
- acm-general-config-policy-application.yaml
- acm-oauth-policy-application.yaml
- acs-central-application.yaml
- application-gitops.yaml
- kustomization.yaml
- quay.yaml

#patchesStrategicMerge:
#- acs-central-declarative-configmap.yaml



